classification:
  max_iter: 500
  class_weight: balanced
  C: 1.0
  random_state: 2

regression:
  input_size: 1
  hidden_size: 20
  num_stacked_layers: 4
  learning_rate: 1e-3
  num_epochs: 100
  scheduler_factor: 0.1
  scheduler_patience: 0
  