{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Drift per time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drift Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM metrics LIMIT 50 "
    }
   ]
  }
 ]
}