services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
      - MODEL_LOCATION=/app/model
      - RUN_ID=8de0cb304e844db8ae045f16c26c71db
      - KINESIS_ENDPOINT_URL=http://kinesis:4566/

  kinesis:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=kinesis