artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://storage.googleapis.com/afrinet/daily-data/AfriNet002.csv
  local_data_file: artifacts/data_ingestion/data.csv

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  look_back: 7
  test_size: 0.2


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  scaler_name: scaler.joblib
  classification_model_name: classification.joblib
  lstm_model_name: lstm.pth
  batch_size: 8


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  scaler_path: artifacts/model_trainer/scaler.joblib
  classifier_path: artifacts/model_trainer/classification.joblib
  regressor_path: artifacts/model_trainer/lstm.pth
  metric_file_name: artifacts/model_evaluation/metrics.json
  mlflow_uri: http://ec2-54-91-2-27.compute-1.amazonaws.com:5000
  batch_size: 8